FROM quay.io/centos7/ruby-27-centos7

ADD . /opt/app-root/src/

USER root

WORKDIR /opt/app-root/src

RUN gem install bundler && \
    bundle install

EXPOSE 4567

CMD ["/opt/rh/rh-ruby27/root/usr/local/bin/bundle", "exec", "middleman", "server"]
