---
name: CI

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Switch to a recent nodejs version as default is nodejs 10 and install NPM.
      - name: Install NPM
        run: |
          dnf -y module switch-to nodejs:14
          dnf install -y nodejs npm

      - name: Install PIP
        run: |
          dnf install -y python3-pip
          
      - name: Install Git
        run: |
          dnf install -y git

      - name: Install required dependencies
        run: |
          pip3 install -r requirements.txt
          npm ci
          
      - name: Run the build
        run: |
          export PATH=$PATH:node_modules/.bin/
          ./build.sh
          
